import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Calendar, CalendarClock, Check, HandCoins, Home, Pencil, Plus, Receipt, RotateCcw, Target, Undo2, Wallet, XCircle } from "lucide-react";
import type { Loan, LoanAccount, LoanStatus } from "./loanTypes";
import { createLoan, deleteLoan, getLoanAccounts, getLoans, repayLoan, updateLoan, updateLoanStatus } from "./loansClient";

type LoansPageProps = { onNavigateDashboard?: () => void; onNavigateMovements?: () => void; onNavigateAccounts?: () => void; onNavigateGoals?: () => void; onNavigateCommitments?: () => void; initialMode?: "list" | "create" | "repay"; initialLoanId?: string | null };
type Mode = "list" | "create" | "edit" | "repay" | "detail";
type LoadState = { status: "loading" } | { status: "error"; message: string } | { status: "success"; loans: Loan[]; pendingTotal: number; pendingCount: number; accounts: LoanAccount[] };
type FormPayload = { persona: string; montoEntregado: number; accountId: string; fecha: string; notas?: string | null };
type RepaymentPayload = { monto: number; accountId: string; fecha: string; notas?: string | null };

const ALLOWED = new Set(["OPERATIVA", "AHORRO", "RESERVA"]);
const TAB_LABELS: Array<[LoanStatus, string]> = [["PENDIENTE", "Pendientes"], ["SALDADO", "Saldados"], ["INCOBRABLE", "Incobrables"]];
const money = (value: number) => `$${Math.abs(Math.round(value)).toLocaleString("es-CL")}`;
const dateLabel = (value: string) => new Intl.DateTimeFormat("es-CL", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));
const today = () => new Date().toISOString().slice(0, 10);
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "No se pudo completar la operación.";

export function LoansPage({ onNavigateDashboard, onNavigateMovements, onNavigateAccounts, onNavigateGoals, onNavigateCommitments, initialMode = "list", initialLoanId = null }: LoansPageProps) {
  const [state, setState] = useState<LoadState>({ status: "loading" });
  const [tab, setTab] = useState<LoanStatus>("PENDIENTE");
  const [mode, setMode] = useState<Mode>(initialMode);
  const [selectedId, setSelectedId] = useState<string | null>(initialLoanId);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [mutationPending, setMutationPending] = useState(false);
  const loadSequence = useRef(0);
  const loadController = useRef<AbortController | null>(null);

  const load = useCallback(async () => {
    loadController.current?.abort();
    const controller = new AbortController();
    loadController.current = controller;
    const sequence = ++loadSequence.current;
    setState((current) => current.status === "success" ? current : { status: "loading" });
    try {
      const [loanData, accountData] = await Promise.all([getLoans(controller.signal), getLoanAccounts(controller.signal)]);
      if (controller.signal.aborted || sequence !== loadSequence.current) return;
      const accounts = accountData.groups.flatMap((group) => group.accounts).filter((account) => ALLOWED.has(account.tipo) && account.activa !== false);
      setState({ status: "success", loans: loanData.loans, pendingTotal: loanData.summary.pendingLoansTotal, pendingCount: loanData.summary.pendingLoansCount, accounts });
    } catch (error) {
      if (controller.signal.aborted || sequence !== loadSequence.current || (error instanceof DOMException && error.name === "AbortError")) return;
      setState({ status: "error", message: "No se pudieron cargar los préstamos. Revisa tu conexión e inténtalo nuevamente." });
    }
  }, []);

  useEffect(() => { void load(); return () => { loadSequence.current += 1; loadController.current?.abort(); }; }, [load]);

  const run = async (operation: (signal: AbortSignal) => Promise<unknown>, success: string) => {
    if (mutationPending) return;
    const controller = new AbortController();
    setMutationPending(true);
    try { await operation(controller.signal); setFeedback(success); setMode("list"); setSelectedId(null); await load(); }
    catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setFeedback(errorMessage(error)); }
    finally { setMutationPending(false); }
  };

  if (state.status === "loading") return <LoansFrame><Status message="Cargando préstamos..." onRetry={() => void load()} /></LoansFrame>;
  if (state.status === "error") return <LoansFrame><Status message={state.message} error onRetry={() => void load()} /></LoansFrame>;
  const selected = state.loans.find((loan) => loan.id === selectedId) ?? null;
  if (mode === "create") return <LoansForm accounts={state.accounts} pending={mutationPending} onBack={() => setMode("list")} onSubmit={(payload) => void run((signal) => createLoan(payload, signal), "Préstamo registrado correctamente.")} />;
  if (mode === "edit" && selected) return <LoansForm loan={selected} accounts={state.accounts} pending={mutationPending} onBack={() => setMode("detail")} onSubmit={(payload) => void run(() => updateLoan(selected.id, payload), "Préstamo actualizado correctamente.")} />;
  if (mode === "repay") return <RepaymentForm loan={selected} loans={state.loans} accounts={state.accounts} pending={mutationPending} onBack={() => setMode(selected ? "detail" : "list")} onSubmit={(id, payload) => void run((signal) => repayLoan(id, payload, signal), "Devolución registrada correctamente.")} />;
  if (mode === "detail" && selected) return <LoanDetail loan={selected} accounts={state.accounts} onBack={() => setMode("list")} onRepay={() => setMode("repay")} onEdit={() => setMode("edit")} onDelete={() => { if (window.confirm(`¿Anular el préstamo de ${selected.persona}? Se revertirá la entrega.`)) void run(() => deleteLoan(selected.id), "Préstamo anulado correctamente."); }} onStatus={(status) => { if (window.confirm(status === "INCOBRABLE" ? "¿Marcar este préstamo como incobrable? No cambia ningún saldo." : "¿Volver este préstamo a pendiente?")) void run(() => updateLoanStatus(selected.id, status), "Estado actualizado correctamente."); }} />;

  const visible = state.loans.filter((loan) => loan.estado === tab);
  const groups = Array.from(new Map(visible.map((loan) => [loan.persona, visible.filter((item) => item.persona === loan.persona)])).entries());
  const counts = Object.fromEntries(TAB_LABELS.map(([status]) => [status, state.loans.filter((loan) => loan.estado === status).length]));
  return <LoansFrame>
    <header className="loans-header"><button className="loans-back" type="button" onClick={onNavigateDashboard}><ArrowLeft size={17} /> Dashboard</button><div><h1>Préstamos</h1><p>Dinero por cobrar</p></div><span /></header>
    {feedback ? <p className="loans-feedback" role="status">{feedback}</p> : null}
    <section className="loans-summary" aria-label="Resumen por cobrar"><p><HandCoins size={15} /> Total por cobrar</p><strong>{money(state.pendingTotal)}</strong><span>{state.pendingCount ? `${state.pendingCount} préstamo${state.pendingCount === 1 ? "" : "s"} pendiente${state.pendingCount === 1 ? "" : "s"}` : "Sin préstamos pendientes"}</span></section>
    <div className="loans-tabs" role="tablist" aria-label="Estado de préstamos">{TAB_LABELS.map(([status, label]) => <button id={`loans-tab-${status}`} type="button" role="tab" aria-controls={`loans-panel-${status}`} aria-selected={tab === status} className={tab === status ? "active" : ""} key={status} onClick={() => setTab(status)}>{label}<span>{counts[status]}</span></button>)}</div>
    <main id={`loans-panel-${tab}`} role="tabpanel" aria-labelledby={`loans-tab-${tab}`} className="loans-content">{groups.length === 0 ? <EmptyLoans status={tab} /> : groups.map(([person, personLoans]) => <section className="loan-person-group" key={person}><div className="loan-person-heading"><h2>{person}</h2><span>{money(personLoans.reduce((sum, loan) => sum + loan.saldoPendiente, 0))}</span></div>{personLoans.map((loan) => <LoanCard key={loan.id} loan={loan} onDetail={() => { setSelectedId(loan.id); setMode("detail"); }} onRepay={() => { setSelectedId(loan.id); setMode("repay"); }} />)}</section>)}</main>
    <button type="button" className="loans-primary-floating" onClick={() => setMode("create")}><Plus size={17} /> Nuevo préstamo</button>
    <BottomNav onNavigateDashboard={onNavigateDashboard} onNavigateMovements={onNavigateMovements} onNavigateAccounts={onNavigateAccounts} onNavigateGoals={onNavigateGoals} onNavigateCommitments={onNavigateCommitments} />
  </LoansFrame>;
}

function LoansFrame({ children }: { children: React.ReactNode }) { return <div className="dashboard-shell"><div className="dashboard-phone loans-phone">{children}</div></div>; }
function Status({ message, error = false, onRetry }: { message: string; error?: boolean; onRetry?: () => void }) { return <div className={`loans-status${error ? " error" : ""}`} role={error ? "alert" : "status"}><span>{message}</span>{onRetry ? <button type="button" className="loans-button" onClick={onRetry}><RotateCcw size={15} /> Reintentar</button> : null}</div>; }
function EmptyLoans({ status }: { status: LoanStatus }) { const text = status === "PENDIENTE" ? "No tienes préstamos pendientes" : status === "SALDADO" ? "Todavía no hay préstamos saldados" : "No tienes préstamos incobrables"; return <div className="loans-empty"><p>{text}</p>{status === "PENDIENTE" ? <span>Registra una entrega para llevar el control del dinero por cobrar usando el botón Nuevo préstamo.</span> : null}</div>; }
function StatusBadge({ status }: { status: LoanStatus }) { return <span className={`loan-status loan-status--${status.toLowerCase()}`}>{status === "PENDIENTE" ? "Pendiente" : status === "SALDADO" ? "Saldado" : "Incobrable"}</span>; }
function LoanCard({ loan, onDetail, onRepay }: { loan: Loan; onDetail: () => void; onRepay: () => void }) { return <article className="loan-card"><div className="loan-card-top"><div><span className="loan-card-label">Saldo pendiente</span><strong>{money(loan.saldoPendiente)}</strong></div><StatusBadge status={loan.estado} /></div><div className="loan-values"><span>Original <b>{money(loan.montoEntregado)}</b></span><span>Devuelto <b>{money(loan.montoEntregado - loan.saldoPendiente)}</b></span></div><div className="loan-meta"><span><Calendar size={12} /> {dateLabel(loan.fechaEntrega)}</span><span>{loan.cuentaEntrega.nombre}</span></div><div className="loan-actions">{loan.estado === "PENDIENTE" ? <button type="button" className="loans-button primary" onClick={onRepay}><Undo2 size={14} /> Registrar devolución</button> : null}<button type="button" className="loans-button" onClick={onDetail}>Ver detalle <ArrowRight size={14} /></button></div></article>; }
function AccountPicker({ accounts, value, onChange, label, balanceOffset = 0 }: { accounts: LoanAccount[]; value: string; onChange: (value: string) => void; label: string; balanceOffset?: number }) { return <fieldset className="loans-fieldset"><legend>{label}</legend><div className="loan-account-list">{accounts.map((account) => <button type="button" key={account.id} className={account.id === value ? "selected" : ""} aria-pressed={account.id === value} onClick={() => onChange(account.id)}><span>{account.nombre}<small>{account.tipo}</small></span>{typeof account.saldo === "number" ? <b>{money(account.saldo + (account.id === value ? balanceOffset : 0))}</b> : null}</button>)}</div>{accounts.length === 0 ? <p className="loans-help">No hay cuentas activas elegibles (Operativa, Ahorro o Reserva).</p> : null}</fieldset>; }

  function LoansForm({ loan, accounts, pending, onBack, onSubmit }: { loan?: Loan; accounts: LoanAccount[]; pending: boolean; onBack: () => void; onSubmit: (payload: FormPayload) => void }) { const [persona, setPersona] = useState(loan?.persona ?? ""); const [amount, setAmount] = useState(String(loan?.montoEntregado ?? "")); const [accountId, setAccountId] = useState(loan?.cuentaEntrega.id ?? accounts[0]?.id ?? ""); const [date, setDate] = useState(loan ? loan.fechaEntrega.slice(0, 10) : today()); const [notes, setNotes] = useState(loan?.notas ?? ""); const account = accounts.find((item) => item.id === accountId); const value = Number(amount); const available = (account?.saldo ?? 0) + (loan?.cuentaEntrega.id === accountId ? loan.montoEntregado : 0); const valid = persona.trim() !== "" && value > 0 && Boolean(accountId) && value <= available; return <LoansFrame><FormHeader title={loan ? "Editar préstamo" : "Nuevo préstamo"} onBack={onBack} /><p className="loans-notice"><HandCoins size={16} /> {loan ? "Solo puede editarse un préstamo sin devoluciones." : "La entrega reduce la cuenta, pero no cuenta como gasto ordinario."}</p><form className="loans-form" onSubmit={(event) => { event.preventDefault(); if (valid && !pending) onSubmit({ persona: persona.trim(), montoEntregado: value, accountId, fecha: date, notas: notes.trim() || null }); }}><label>Persona<input required value={persona} onChange={(event) => setPersona(event.target.value)} placeholder="Nombre de la persona" /></label><label>Monto entregado<input required type="number" min="1" step="1" value={amount} onChange={(event) => setAmount(event.target.value)} />{value > available ? <small className="field-error">Supera el saldo disponible de {money(available)}.</small> : null}</label><AccountPicker accounts={accounts} value={accountId} onChange={setAccountId} label="Cuenta de origen" balanceOffset={loan?.cuentaEntrega.id === accountId ? loan.montoEntregado : 0} /><label>Fecha de entrega<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Notas (opcional)<textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className="loans-button primary submit" type="submit" disabled={!valid || pending}>{pending ? "Registrando préstamo..." : loan ? "Guardar cambios" : "Registrar préstamo"}</button></form></LoansFrame>; }
function FormHeader({ title, onBack }: { title: string; onBack: () => void }) { return <header className="loans-header form-header"><button className="loans-back" type="button" onClick={onBack}><ArrowLeft size={17} /> Volver</button><h1>{title}</h1><span /></header>; }
  function RepaymentForm({ loan, loans, accounts, pending, onBack, onSubmit }: { loan: Loan | null; loans: Loan[]; accounts: LoanAccount[]; pending: boolean; onBack: () => void; onSubmit: (id: string, payload: RepaymentPayload) => void }) { const [loanId, setLoanId] = useState(loan?.id ?? ""); const current = loans.find((item) => item.id === loanId) ?? null; const [amount, setAmount] = useState(""); const [accountId, setAccountId] = useState(accounts[0]?.id ?? ""); const [date, setDate] = useState(today()); const [notes, setNotes] = useState(""); const value = Number(amount); const valid = Boolean(current && accountId && value > 0 && value <= current.saldoPendiente); return <LoansFrame><FormHeader title="Registrar devolución" onBack={onBack} /><p className="loans-notice"><Undo2 size={16} /> La devolución aumenta la cuenta destino, pero no cuenta como ingreso ordinario.</p><form className="loans-form" onSubmit={(event) => { event.preventDefault(); if (valid && current && !pending) onSubmit(current.id, { monto: value, accountId, fecha: date, notas: notes.trim() || null }); }}>{!loan ? <label>Préstamo pendiente<select value={loanId} onChange={(event) => setLoanId(event.target.value)}><option value="">Selecciona un préstamo</option>{loans.filter((item) => item.estado === "PENDIENTE").map((item) => <option key={item.id} value={item.id}>{item.persona} · {money(item.saldoPendiente)}</option>)}</select></label> : null}{current ? <div className="repayment-balance"><span>{current.persona}</span><strong>Saldo {money(current.saldoPendiente)}</strong></div> : null}<label>Monto devuelto<input required type="number" min="1" max={current?.saldoPendiente} step="1" value={amount} onChange={(event) => setAmount(event.target.value)} />{current && value > current.saldoPendiente ? <small className="field-error">No puede superar el saldo pendiente de {money(current.saldoPendiente)}.</small> : null}</label><AccountPicker accounts={accounts} value={accountId} onChange={setAccountId} label="Cuenta donde ingresa el dinero" /><label>Fecha<input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Notas (opcional)<textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className="loans-button primary submit" type="submit" disabled={!valid || pending}>{pending ? "Registrando devolución..." : "Registrar devolución"}</button></form></LoansFrame>; }
function LoanDetail({ loan, accounts, onBack, onRepay, onEdit, onDelete, onStatus }: { loan: Loan; accounts: LoanAccount[]; onBack: () => void; onRepay: () => void; onEdit: () => void; onDelete: () => void; onStatus: (status: "PENDIENTE" | "INCOBRABLE") => void }) { const hasRepayments = loan.devoluciones.length > 0; const origin = accounts.find((account) => account.id === loan.cuentaEntrega.id) ?? loan.cuentaEntrega; return <LoansFrame><FormHeader title="Detalle del préstamo" onBack={onBack} /><section className="loan-detail-hero"><p>{loan.persona}</p><strong>{money(loan.saldoPendiente)}</strong><StatusBadge status={loan.estado} /></section><dl className="loan-detail-data"><dt>Monto original</dt><dd>{money(loan.montoEntregado)}</dd><dt>Total devuelto</dt><dd>{money(loan.montoEntregado - loan.saldoPendiente)}</dd><dt>Cuenta de origen</dt><dd>{origin.nombre}</dd><dt>Fecha de entrega</dt><dd>{dateLabel(loan.fechaEntrega)}</dd></dl><section className="repayment-history"><h2>Historial de devoluciones</h2>{loan.devoluciones.length === 0 ? <p className="loans-help">Todavía no se registró ninguna devolución.</p> : loan.devoluciones.map((repayment) => <div className="repayment-row" key={repayment.id}><strong>{money(repayment.monto)}</strong><span>{dateLabel(repayment.fecha)}</span><small>Recibido en {repayment.cuentaDestino.nombre}{repayment.notas ? ` · ${repayment.notas}` : ""}</small></div>)}</section><div className="loan-detail-actions">{loan.estado === "PENDIENTE" ? <button type="button" className="loans-button primary" onClick={onRepay}><Undo2 size={14} /> Registrar devolución</button> : null}{!hasRepayments && loan.estado === "PENDIENTE" ? <><button type="button" className="loans-button" onClick={onEdit}><Pencil size={14} /> Editar</button><button type="button" className="loans-button danger" onClick={onDelete}>Anular</button></> : null}{hasRepayments && loan.estado !== "SALDADO" ? <p className="loans-help">Con devoluciones registradas no se puede editar ni anular este préstamo.</p> : null}{loan.estado === "PENDIENTE" ? <button type="button" className="loans-button danger" onClick={() => onStatus("INCOBRABLE")}><XCircle size={14} /> Marcar como incobrable</button> : null}{loan.estado === "INCOBRABLE" ? <button type="button" className="loans-button" onClick={() => onStatus("PENDIENTE")}><RotateCcw size={14} /> Volver a pendiente</button> : null}</div></LoansFrame>; }
  function BottomNav({ onNavigateDashboard, onNavigateMovements, onNavigateAccounts, onNavigateGoals, onNavigateCommitments }: Pick<LoansPageProps, "onNavigateDashboard" | "onNavigateMovements" | "onNavigateAccounts" | "onNavigateGoals" | "onNavigateCommitments">) { const items = [{ key: "dashboard", label: "Dash", icon: Home, onClick: onNavigateDashboard }, { key: "movements", label: "Mov", icon: Receipt, onClick: onNavigateMovements }, { key: "accounts", label: "Cta", icon: Wallet, onClick: onNavigateAccounts }, { key: "goals", label: "Meta", icon: Target, onClick: onNavigateGoals }, { key: "commitments", label: "Compr", icon: CalendarClock, onClick: onNavigateCommitments }]; return <nav className="dashboard-bottom-nav" aria-label="Navegación principal"><div className="dashboard-bottom-nav-inner">{items.map(({ key, label, icon: Icon, onClick }) => <button key={key} type="button" className="dashboard-nav-item" onClick={onClick}><Icon size={20} /><span>{label}</span></button>)}</div></nav>; }
export default LoansPage;
